#!c:\users\akhan\desktop\github\python-django-api\env\scripts\python.exe
import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from htmlparser import standalone

standalone.main()
